### ISSUE TITLE
Nothing is slow until you've profiled it - Alan Shreve

### ISSUE THREAD

**Issue by dlsniper** [go-proverbs/go-proverbs.github.io#13]
Alan just dropped this one in Slack and I feel it should be added to the list:

```
Nothing is slow until you've profiled it
```

Source: https://gophers.slack.com/archives/general/p1457045009014382
Thank you.

**Comment by HarveyKandola** [comment]
Thank you. This will be reviewed by the core team in due course.

**Comment by dlsniper** [comment]
About that review :D

**Comment by robpike** [comment]
I don't have a Slack account, but I can review it here.

The proposed proverb is clever but does not pertain specifically to Go. Also, I'm not sure I even believe it. There are lots of things I know of that are slow that I haven't profiled.

There may be an idea here, but the proposed proverb does not capture it.
