### ISSUE TITLE
Gofmt at the start of the sentence should be gofmt.

### ISSUE THREAD

**Issue by RalphCorderoy** [go-proverbs/go-proverbs.github.io#6]
Commands aren't capitalised as they're case sensitive.  Similarly, it remains interface when at the start of a line nearby.

**Comment by HarveyKandola** [comment]
These are as received from Rob Pike.

I think they are meant to read as proverbs and not commands.

**Comment by robpike** [comment]
English sentences start with capital letters. I disagree with your assertion here. There is no true confusion if we use English rules when writing English sentences that contain code.
