### ISSUE TITLE
Go is (almost) everywhere.

### ISSUE THREAD

**Issue by theclapp** [go-proverbs/go-proverbs.github.io#9]
Windows, Linux, Mac, iOS, Android, browsers*, Google App Engine, Amazon, Raspberry Pi ... Chances are, whatever you want to do, wherever you want to do it, you can do it in Go.

*browsers: see GopherJS

Other possible phrasings:
Go is ubiquitous, or ubiquitous _enough_.
Go is everywhere you want to be.  (h/t Visa)  If it doesn't do Go, you probably don't want to be there.  :)

**Comment by HarveyKandola** [comment]
Many thanks.

I believe the proverbs should be focused teaching the Go way.

**Comment by theclapp** [comment]
The Go way is to write in Go.  Which is everywhere.  :)

No worries, I don't feel strongly about it.
